#---------- Prelogin and Login----------
Prelogin_advanceButton                      = Xpath;//*[@id="details-button"]
Prelogin_proceedLink                        = Xpath;//*[@id="proceed-link"]
Prelogin_usernameField                      = Xpath;//*[@id="Input_NamaUser"]
Prelogin_passwordField                      = Xpath;//*[@id="Input_Password"]
Prelogin_loginButton                        = Xpath;//*[@id="BtnLogin"]/div/button

#---------- Home Page ----------
Home_userProfile                            = Xpath;//*[@id="b2-b3-b1-Content"]
Home_backofficeDropdown                     = Xpath;//*[@id="b2-l2-17_1-b2-SubMenuHeader"] | //*[@id="b2-l2-17_1-b2-Menu"] | //*[contains(text(), 'BackOffice')]
Home_BONotaKredit                           = Xpath;//*[text()='Nota Bulk Payroll']
Home_logoutButton                           = Xpath;//*[@id="b2-b3-Icon3"]
Home_approvalPejabat                        = Xpath;//*[contains(text(),"Approval DeptHead")]
Home_approvalSPV                            = Xpath;//span[normalize-space()="Approval SPV"]

#---------- Nota Bulk Page ----------
NotaBulk_notaBulkTitle                      = Xpath;//*[@id="b1-Title"]/span
NotaBulk_transactionType                    = Xpath;//*[@id="Dropdown_TransactionType"]
NotaBulk_notaBulkCredit                     = Xpath;(//*[contains(text(), 'Nota Bulk - Payroll')])[1]
NotaBulk_kebutuhanTrxNonExist               = Xpath;//*[@id="RadioButton2-input"]
NotaBulk_accountTypeBluaccount              = Xpath;//*[@id="RadioButton3-input"]
NotaBulk_releaseTimeNow                     = Xpath;//*[@id="RB_ReleaseTime_Noww-input"]
NotaBulk_fileNota                           = Xpath;//*[@id="NotaBulk_FileNota"]/input
NotaBulk_attachmentNota                     = Xpath;//*[@id="NotaBulk_FileLampiran"]/input
NotaBulk_checkValidityButton                = Xpath;//*[@id="Container_Button"]/button | //*[contains(text(),'Check Validity FIle')]
NotaBulk_ValidTransaction                   = Xpath;//*[contains(text(),'6 transaction(s)')]
NotaBulk_NominalTransaction                 = Xpath;//*[contains(text(),'Rp 390.000.000,00')]
NotaBulk_submitButton                       = Xpath;//*[contains(text(),'Submit')]

#---------- Approval Pejabat Page ----------
ApprovalPejabat_title                       = Xpath;//*[@id="b1-Title"]/span
ApprovalPejabat_transactionTypeDropdown     = Xpath;//*[@id="DropdownTransactionType-container"]/option[1] | //*[@id="DropdownTransactionType"]
ApprovalPejabat_transactionType             = Xpath;//*[contains(text(), 'Nota Bulk - Kredit')]
ApprovalPejabat_approveButton               = Xpath;(//*[normalize-space()="Approve"])[1]

#---------- Approval SPV Page ----------
ApprovalSPV_title                           = Xpath;//*[@class="head2" and @text="Approval SPV"]
ApprovalSPV_transactionType                 = Xpath;//*[@id="DropdownTransactionType"]
ApprovalSPV_notaBulkCredit                  = Xpath;(//*[contains(text(), 'Nota Bulk - Kredit')])[1]
ApprovalSPV_approveButton                   = Xpath;(//*[contains(@id,"ApproveButton3")])[1]
ApprovalSPV_notaBulkProcessedCloseButton    = Xpath;//*[@id="PopUpShowSuccessOrFailedApproved"]/div/div[1]/div[2]/i
